# Generated by Django 5.1.7 on 2025-03-20 07:50

import PazarBet.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), PazarBet.core.validators.validate_only_letters]),
        ),
    ]
