# Generated by Django 5.1.7 on 2025-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('DoNotShow', 'Do Not Show')], max_length=9, null=True),
        ),
    ]
